from __future__ import annotations

USER_IMPORT_RETRY_DELAYS_SECONDS = (2, 2, 2)
USER_IMPORT_PROCESSING_CLAIM_MINUTES = 15
USER_IMPORT_BUILD_FAILED_RETRY_COOLDOWN_HOURS = 24
USER_IMPORT_MAX_DOC_SYNCS_PER_RUN = 10
USER_IMPORT_MAX_JOBS_PER_RUN = 10
WORDNIK_RUNTIME_STATE_KEY = "user_import_wordnik_quota"
USER_IMPORT_DETAILS_SCHEDULE_STATE_KEY = "user_import_details_schedule"
USER_IMPORT_AUDIO_SCHEDULE_STATE_KEY = "user_import_audio_schedule"
